# Generated by Django 4.0.2 on 2022-02-02 17:23

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilization',
            name='Year',
            field=models.CharField(default=dashboard.models.current_year, max_length=4),
        ),
    ]
