# Generated by Django 4.0.2 on 2022-02-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilization',
            name='year',
            field=models.IntegerField(default=2022),
            preserve_default=False,
        ),
    ]
