# Generated by Django 4.0.2 on 2022-02-15 11:02

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Samples',
            fields=[
                ('TestID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Test', models.CharField(max_length=100)),
                ('January', models.FloatField()),
                ('February', models.FloatField()),
                ('March', models.FloatField()),
                ('April', models.FloatField()),
                ('June', models.FloatField()),
                ('July', models.FloatField()),
                ('August', models.FloatField()),
                ('September', models.FloatField()),
                ('October', models.FloatField()),
                ('November', models.FloatField()),
                ('December', models.FloatField()),
                ('Year', models.IntegerField(default=dashboard.models.current_year)),
            ],
        ),
        migrations.DeleteModel(
            name='Processed',
        ),
        migrations.AlterField(
            model_name='revenue',
            name='TestID',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='utilization',
            name='AssayID',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
