# Generated by Django 4.0.2 on 2022-02-16 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='stats',
            fields=[
                ('AssayID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('FullCapacity', models.FloatField()),
                ('RunTime', models.FloatField()),
                ('Price', models.FloatField()),
            ],
        ),
    ]
