# Generated by Django 4.0.2 on 2022-02-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_stats'),
    ]

    operations = [
        migrations.CreateModel(
            name='monthlystats',
            fields=[
                ('AssayID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('MaxMonthlyhours', models.FloatField()),
                ('MaxMonthlyRevenue', models.FloatField()),
                ('MaxMonthSamples', models.FloatField()),
            ],
        ),
    ]
