# Generated by Django 4.0.2 on 2022-02-05 06:29

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_utilization_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processed',
            fields=[
                ('TestID', models.AutoField(primary_key=True, serialize=False)),
                ('Test', models.CharField(max_length=100)),
                ('January', models.FloatField()),
                ('February', models.FloatField()),
                ('March', models.FloatField()),
                ('April', models.FloatField()),
                ('June', models.FloatField()),
                ('July', models.FloatField()),
                ('August', models.FloatField()),
                ('September', models.FloatField()),
                ('October', models.FloatField()),
                ('November', models.FloatField()),
                ('December', models.FloatField()),
                ('Year', models.IntegerField(default=dashboard.models.current_year)),
                ('MonthlyIndex', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('TestID', models.AutoField(primary_key=True, serialize=False)),
                ('Test', models.CharField(max_length=100)),
                ('January', models.FloatField()),
                ('February', models.FloatField()),
                ('March', models.FloatField()),
                ('April', models.FloatField()),
                ('June', models.FloatField()),
                ('July', models.FloatField()),
                ('August', models.FloatField()),
                ('September', models.FloatField()),
                ('October', models.FloatField()),
                ('November', models.FloatField()),
                ('December', models.FloatField()),
                ('Year', models.IntegerField(default=dashboard.models.current_year)),
                ('MonthlyIndex', models.FloatField()),
            ],
        ),
    ]
