# Generated by Django 4.0.2 on 2022-02-16 09:53

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_monthlystats'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissedRevenue',
            fields=[
                ('AssayID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Assay', models.CharField(max_length=100)),
                ('January', models.FloatField()),
                ('February', models.FloatField()),
                ('March', models.FloatField()),
                ('April', models.FloatField()),
                ('May', models.FloatField()),
                ('June', models.FloatField()),
                ('July', models.FloatField()),
                ('August', models.FloatField()),
                ('September', models.FloatField()),
                ('October', models.FloatField()),
                ('November', models.FloatField()),
                ('December', models.FloatField()),
                ('Year', models.IntegerField(default=dashboard.models.current_year)),
            ],
        ),
    ]
